package blueprint.entities.gauge;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

interface GaugeConfiguration
{
	
	function getThreshold(): Float;
	
	function getMaximum(): Float;
	
}