package blueprint.entities.gauge;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

interface GaugeConfigurator<T>
{
	
	function threshold(value: Float): T;
	
	function maximum(value: Float): T;
	
}