package blueprint.entities.button;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

class Button
	extends Node
	implements ButtonConfiguration
	implements ConnectableSource
	
{
	/* VARIABLES */

	private var _minimum: Float = 0;

	private var _maximum: Float = 1;

	private var _enabled: Bool = false;

	private var _output: Float = 0;

	/* CONSTRUCTOR  */
	private function new(template: ButtonTemplate)
	{
		super();
		
		this._minimum = template.getMinimum();
		
		this._maximum = template.getMaximum();
		
		this._enabled = template.getEnabled();
		
	}
	/* GETTERS */

	public function getMinimum(): Float { return this._minimum; }

	public function getMaximum(): Float { return this._maximum; }

	public function getEnabled(): Bool { return this._enabled; }

	public function getOutput(): Float { return this._output; }


	/* INTERFACE ConnectableSource */
	public function getOutgoingConnections():Array<Connection> { return _outgoingConnections; }
	public function connectAsSource(connection:Connection) { _outgoingConnections.push(connection); }


	/* INTERFACE ConnectableDestination */
	public function getIngoingConnections():Array<Connection> { return _ingoingConnections; }
	public function connectAsDestination(connection:Connection) { _ingoingConnections.push(connection); }

}