package blueprint.entities.button;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

interface ButtonConfigurator<T>
{
	
	function minimum(value: Float): T;
	
	function maximum(value: Float): T;
	
	function enabled(value: Bool): T;
	
}