package blueprint.entities.button;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

interface ButtonConfiguration
{
	
	function getMinimum(): Float;
	
	function getMaximum(): Float;
	
	function getEnabled(): Bool;
	
}