package blueprint.entities.button;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

class MutableButton extends Button
{
	public function new(template: ButtonTemplate)
	{
		super(template);
	}
	
	public function setEnabled(value: Bool) { this._enabled = value; }
	
	public function setOutput(value: Float) { this._output = value; }
	
}