package blueprint.entities.neuron;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

interface NeuronConfigurator<T>
{
	
	function threshold(value: Float): T;
	
	function maximum(value: Float): T;
	
	function factor(value: Float): T;
	
}