package blueprint.entities.neuron;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

interface NeuronConfiguration
{
	
	function getThreshold(): Float;
	
	function getMaximum(): Float;
	
	function getFactor(): Float;
	
}