package blueprint.entities.light;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

class MutableLight extends Light
{
	public function new(template: LightTemplate)
	{
		super(template);
	}
	
	public function setEnabled(value: Bool) { this._enabled = value; }
	
	public function setInput(value: Float) { this._input = value; }
	
}