package blueprint.entities.gauge;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

class MutableGauge extends Gauge
{
	public function new(template: GaugeTemplate)
	{
		super(template);
	}
	
	public function setInput(value: Float) { this._input = value; }
	
	public function setPosition(value: Float) { this._position = value; }
	
}