package simulations {
  interface ModuleRuntimeData {
    +instance: ModuleInstance
    +nodes: Map<int, NodeRuntimeData>
    +connections: Map<int, ConnectionRuntimeData>
    +getInput(): Json
    +setInput(input: Json)
    +getState(): Json
    +setState(state: Json)
    +getOutput(): Json
    +setOutput(output: Json)
  }

  interface NodeRuntimeData {
    +<<read only>>type: NeuronType
    +<<read only>>ingoingConnections: ConnectionRuntimeData[]
    +<<read only>>outgoingConnections: ConnectionRuntimeData[]
    +<<write only>>output: Hash
    +<<read only>>input: Hash
    +<<read only>>state: Hash
    +<<write only>>newState: Hash
  }

  interface ConnectionRuntimeData {
    +<<write only>>output: Hash
    +<<read only>>input: Hash
    +<<read only>>state: Hash
    +<<write only>>newState: Hash
    +<<read only>>source: NodeRuntimeData
    +<<read only>>destination: NodeRuntimeData
  }
  ConnectionRuntimeData "*" o--o "2" NodeRuntimeData

  NodeRuntimeData --o ModuleRuntimeData
  ConnectionRuntimeData --o ModuleRuntimeData
}