package blueprint.entities.slider;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

interface SliderConfigurator<T>
{
	
	function minimum(value: Float): T;
	
	function maximum(value: Float): T;
	
	function position(value: Float): T;
	
}