package {{:package}};

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD! 
 */

interface {{:entityName}}Configuration 
{
	{{for variables}}{{if configurable}}
	function get{{:name.capitalize()}}(): {{:type}};
	{{/if}}{{/for}}
}