package {{:package}};

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD! 
 */

interface {{:entityName}}Configurator<T>
{
	{{for variables}}{{if configurable}}
	function {{:name}}(value: {{:type}}): T;
	{{/if}}{{/for}}
}