package blueprint.entities.random;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

class MutableRandom extends Random
{
	public function new(template: RandomTemplate)
	{
		super(template);
	}
	
	public function setOutput(value: Float) { this._output = value; }
	
}