package blueprint.entities.random;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

import blueprint.entities.Builder;
import blueprint.entities.instance.ModuleInstanceBuilder;
import blueprint.entities.TemplateBuilder;
import blueprint.Error;

class RandomBuilder
	implements RandomConfigurator<RandomBuilder>
	implements NameConfigurator<RandomBuilder>
	implements Builder<Random>
	implements TemplateBuilder<RandomTemplate>
{
	/* VARIABLES */
	private var _moduleInstanceBuilder: ModuleInstanceBuilder;
	private var _finished: Bool = false;
	private var _name: String = null;
	
	private var _minimum: Float;
	
	private var _maximum: Float;
	
	private var _seed: Int;
	

	/* CONSTRUCTOR */
	public function new(instanceBuilder: ModuleInstanceBuilder, template: RandomTemplate)
	{
		this._moduleBuilder = moduleBuilder;
		
		this._minimum = template.getMinimum();
		
		this._maximum = template.getMaximum();
		
		this._seed = template.getSeed();
		
	}

	/* INTERFACE Builder<Random> */
	public function build(): Random
	{
		if (this._finished)
			throw new Error("Random was already built!");
		var entity = new Random(template());
		_moduleBuilder.add(entity);
		if(this._name != null)
			_moduleBuilder.alias(name, entity);
		this._finished = true;
		return entity;
	}

	/* INTERFACE TemplateBuilder<Random> */
	public function template(): RandomTemplate
	{
		var result = new RandomTemplate();
		
		result.minimum(this._minimum);
		
		result.maximum(this._maximum);
		
		result.seed(this._seed);
		
		return result;
	}

	/* INTERFACE RandomConfigurator<RandomBuilder> */
	
	public function minimum(value: Float): RandomBuilder
	{
		this._minimum = value;
		return this;
	}
	
	public function maximum(value: Float): RandomBuilder
	{
		this._maximum = value;
		return this;
	}
	
	public function seed(value: Int): RandomBuilder
	{
		this._seed = value;
		return this;
	}
	

	/* INTERFACE NameConfigurator<RandomBuilder> */
	public function name(name:String): RandomBuilder
	{
		this._name = name;
		return this;
	}
}
