package {{:package}};

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD! 
 */

class Mutable{{:entityName}} extends {{:entityName}}
{
	public function new(template: {{:entityName}}Template) 
	{
		super(template);
	}
	{{for variables}}{{if mutable}}
	public function set{{:name.capitalize()}}(value: {{:type}}) { this._{{:name}} = value; }
	{{/if}}{{/for}}
}