package blueprint.entities.slider;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

interface SliderConfiguration
{
	
	function getMinimum(): Float;
	
	function getMaximum(): Float;
	
	function getPosition(): Float;
	
}