package blueprint.entities.slider;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

class SliderTemplate
	implements SliderConfigurator<SliderTemplate>
	implements SliderConfiguration
{
	
	private var _minimum: Float = 0;
	
	private var _maximum: Float = 1;
	
	private var _position: Float = 0;
	

	
	public function getMinimum(): Float { return _minimum; }
	
	public function getMaximum(): Float { return _maximum; }
	
	public function getPosition(): Float { return _position; }
	

	/* INTERFACE SliderConfigurator<SliderTemplate> */
	
	public function minimum(value: Float): SliderTemplate { _minimum = value; return this; }
	
	public function maximum(value: Float): SliderTemplate { _maximum = value; return this; }
	
	public function position(value: Float): SliderTemplate { _position = value; return this; }
	
}