package blueprint.entities.random;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

interface RandomConfiguration
{
	
	function getMinimum(): Float;
	
	function getMaximum(): Float;
	
	function getSeed(): Int;
	
}