package blueprint.entities.random;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

interface RandomConfigurator<T>
{
	
	function minimum(value: Float): T;
	
	function maximum(value: Float): T;
	
	function seed(value: Int): T;
	
}