package blueprint.entities.neuron;

/* THIS FILE WAS GENERATED BY THE 'generate-entity' tool.
 * DO NOT CHANGE ANYTHING HERE! CHANGE THE TEMPLATES INSTEAD!
 */

class MutableNeuron extends Neuron
{
	public function new(template: NeuronTemplate)
	{
		super(template);
	}
	
	public function setInput(value: Float) { this._input = value; }
	
	public function setOutput(value: Float) { this._output = value; }
	
}